### PR TITLE
Fix additional_header parameter and refactor OCSClient

### PR DESCRIPTION
**Pull request by anton-dahlin**
This PR renames the _headers_ parameter used in Streams client to _additional_headers_ to fit the recent addition of additional_headers. This was throwing argument error when the SharedStreams client was calling the Streams client using additional_headers=*** as the parameter was still called _headers_.

It also refactors the OCSClient based on [feedback](https://github.com/osisoft/sample-ocs-sample_libraries-python/pull/44#discussion_r797841071) from Kelsey to avoid having to maintain both ADH and OCS clients separately.

### CODE REVIEW

**Review by kelseyduffy — CHANGES_REQUESTED** [review]
If I'm understanding these headers -> additional_headers renamings correctly, these would be breaking changes for anyone that is using a named argument for 'headers' since that parameter doesn't exist anymore. The library's base client also handles 'headers' differently from 'additional_headers' (headers prevents the base client from getting its own standard headers, additional headers doesnt), so there could in theory be different behavior with this change.

**Comment by anton-dahlin** [comment]
> If I'm understanding these headers -> additional_headers renamings correctly, these would be breaking changes for anyone that is using a named argument for 'headers' since that parameter doesn't exist anymore. The library's base client also handles 'headers' differently from 'additional_headers' (headers prevents the base client from getting its own standard headers, additional headers doesnt), so there could in theory be different behavior with this change.

I am a little torn between changing the Streams or SharedStreams client... Changing the Streams would as you say be a breaking change, but follows the pattern of additional headers better since we just provide the one header we want to add, since headers will be None at the request level and be set to its default Sds Headers. 

If we leave Streams as is we would have to get the Sds Headers and add the CommunityId header in the SharedStreams client to then send as the headers parameter, which would essentially undo the additional headers pattern.

We could also add a additional_headers parameter to the Streams client, that wouldn't be breaking any current code, but it doesn't really make any sense to me since you are providing the headers and then overrides to those headers, so pretty redundant.

What are your thoughts?

**Comment by kelseyduffy** [comment]
In the case of keeping both, headers and additional_headers, we'd need to make the notes clear that 'headers' is for entirely blocking the base client's built in headers call, and the caller is now responsible for providing all required headers; and that additional_headers are entirely supplemental. A normal useage of this would be headers=None, additional_headers={'something': 'some value'}

**Comment by anton-dahlin** [comment]
> I guess my thoughts were that the workflow for the headers parameter wouldnt change in case anyone was using it where it blocks the base client's headers call. Then there would be a separate parameter for values that the user wanted to override or add to the base client's headers call. I think the second one is a lot smoother in general and a much more usable scenario, but the first way is how it's been working for the entire time the client has been released, so it's not that great of an option to entirely end it.
> 
> I'm kind of split though in general because anyone trying to use these will almost certainly get confused as to why there's a headers and additional_headers parameter on the functions, and if we pick one I definitely would pick the functionality of the additional_headers parameter.

@kelseyduffy based on our conversation, I kept the rename from headers to additional_headers and provided a better context in the history file

**Review by cbardini — APPROVED** [review]

**Review by kelseyduffy — APPROVED** [review]

**Pull request merged**
